# Main docker-compose configuration
services:
  # ==================== API GATEWAY ====================
  nginx-gateway:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    env_file:
      - ./.env
    depends_on:
      - main-service
      - auth-service
      - medias-service
      - user-permission-gateway
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/nginx-health"]
      interval: 30s
      timeout: 5s
      retries: 3
    command: >
      sh -c "envsubst '$$FRONTEND_URL' < /etc/nginx/conf.d/default.conf > /tmp/default.conf && 
             mv /tmp/default.conf /etc/nginx/conf.d/default.conf && 
             nginx -g 'daemon off;'"

  # ==================== MICROSERVICES ====================
  main-service:
    build:
      context: .
      dockerfile: ./main-service/Dockerfile
      args:
        PORT: ${MAIN_SERVICE_PORT}
    env_file:
      - ./.env
      - ./main-service/.env
    # Ports removed - only accessible via Nginx Gateway
    depends_on:
      - db
      - auth-service
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${MAIN_SERVICE_PORT}/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
      args:
        PORT: ${AUTH_SERVICE_PORT}
    env_file:
      - ./.env
      - ./auth-service/.env
    # Ports removed - only accessible via Nginx Gateway
    depends_on:
      - db
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${AUTH_SERVICE_PORT}/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  medias-service:
    build:
      context: .
      dockerfile: ./medias-service/Dockerfile
      args:
        PORT: ${MEDIAS_SERVICE_PORT}
    env_file:
      - ./.env
      - ./medias-service/.env
    # Ports removed - only accessible via Nginx Gateway
    depends_on:
      - medias-db
      - rabbitmq
      - auth-service
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${MEDIAS_SERVICE_PORT}/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  user-permission-gateway:
    build:
      context: .
      dockerfile: ./user-permission-gateway/Dockerfile
      args:
        PORT: ${USER_PERMISSION_GATEWAY_PORT}
    env_file:
      - ./.env
      - ./user-permission-gateway/.env
    # Ports removed - only accessible via Nginx Gateway
    depends_on:
      - db
      - rabbitmq
      - main-service
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${USER_PERMISSION_GATEWAY_PORT}/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Main Service Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT_INTERNAL}"
    volumes:
      - main_postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  # Medias Service Database
  medias-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${MEDIAS_DB_NAME}
      POSTGRES_USER: ${MEDIAS_DB_USERNAME}
      POSTGRES_PASSWORD: ${MEDIAS_DB_PASSWORD}
    ports:
      - "${MEDIAS_DB_PORT_EXTERNAL}:${MEDIAS_DB_PORT_INTERNAL}"
    volumes:
      - medias_postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT_EXTERNAL}:${RABBITMQ_PORT_INTERNAL}"
      - "${RABBITMQ_MANAGEMENT_PORT_EXTERNAL}:${RABBITMQ_MANAGEMENT_PORT_INTERNAL}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend-network

volumes:
  main_postgres_data:
  medias_postgres_data:
  rabbitmq_data:

networks:
  backend-network:
    driver: bridge
