# Development configuration - Simple version
services:
  # Development overrides for services
  main-service:
    build:
      context: .
      dockerfile: ./main-service/Dockerfile
      target: development
    volumes:
      - ./main-service:/app/main-service
      - ./shared-common:/app/shared-common
      - /app/node_modules
    environment:
      - NODE_ENV=development

  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
      target: development
    volumes:
      - ./auth-service:/app/auth-service
      - ./shared-common:/app/shared-common
    environment:
      - NODE_ENV=development

  media-service:
    build:
      context: .
      dockerfile: ./media-service/Dockerfile
      target: development
    volumes:
      - ./media-service:/app/media-service
      - ./shared-common:/app/shared-common
      - /app/node_modules
      - ./storage:/app/storage
    environment:
      - NODE_ENV=development

  user-permission-gateway:
    build:
      context: .
      dockerfile: ./user-permission-gateway/Dockerfile
      target: development
    volumes:
      - ./user-permission-gateway:/app/user-permission-gateway
      - ./shared-common:/app/shared-common
      - /app/node_modules
    environment:
      - NODE_ENV=development
