export type DomainType = string;

export type ActionType = string;

export const DOMAINS = {
  ARTICLES: {
    value: 'articles',
    actions: {
      VIEW: 'view',
      CREATE: 'create',
      EDIT_OWN: 'edit_own',
      EDIT_ALL: 'edit_all',
      DELETE_OWN: 'delete_own',
      DELETE_ALL: 'delete_all',
      PUBLISH: 'publish',
      UNPUBLISH: 'unpublish',
      REVIEW: 'review',
      MODERATE: 'moderate',
      ARCHIVE: 'archive',
      FEATURE: 'feature',
      PIN: 'pin',
      SCHEDULE: 'schedule',
      DUPLICATE: 'duplicate',
      TRANSLATE: 'translate',
      EXPORT: 'export',
      IMPORT: 'import',
      BULK_EDIT: 'bulk_edit',
      BULK_DELETE: 'bulk_delete',
      VIEW_ANALYTICS: 'view_analytics',
      MANAGE_VERSIONS: 'manage_versions',
    },
  },
  COMMENTS: {
    value: 'comments',
    actions: {
      VIEW: 'view',
      CREATE: 'create',
      EDIT_OWN: 'edit_own',
      DELETE_OWN: 'delete_own',
      DELETE_ALL: 'delete_all',
      MODERATE: 'moderate',
      REPORT: 'report',
      REPLY: 'reply',
      LIKE: 'like',
      BULK_MODERATE: 'bulk_moderate',
      BULK_DELETE: 'bulk_delete',
      APPROVE: 'approve',
      SPAM: 'spam',
      BAN_USER: 'ban_user',
    },
  },
  USERS: {
    value: 'users',
    actions: {
      VIEW: 'view',
      EDIT: 'edit',
      ASSIGN_ROLE: 'assign_role',
      CREATE: 'create',
      DELETE: 'delete',
      BLOCK: 'block',
      UNBLOCK: 'unblock',
      CHANGE_PASSWORD: 'change_password',
      RESET_PASSWORD: 'reset_password',
      VERIFY: 'verify',
      BULK_EDIT: 'bulk_edit',
      BULK_DELETE: 'bulk_delete',
      BULK_BLOCK: 'bulk_block',
      EXPORT: 'export',
      IMPORT: 'import',
      VIEW_ACTIVITY: 'view_activity',
      MANAGE_PREFERENCES: 'manage_preferences',
    },
  },
  ROLES: {
    value: 'roles',
    actions: {
      VIEW: 'view',
      VIEW_SUMMARY: 'view_summary',
      CREATE: 'create',
      EDIT: 'edit',
      DELETE: 'delete',
      ASSIGN_PERMISSION: 'assign_permission',
    },
  },
  CATEGORIES: {
    value: 'categories',
    actions: {
      VIEW: 'view',
      CREATE: 'create',
      EDIT: 'edit',
      DELETE: 'delete',
      MANAGE: 'manage',
    },
  },
  TAGS: {
    value: 'tags',
    actions: {
      VIEW: 'view',
      CREATE: 'create',
      EDIT: 'edit',
      DELETE: 'delete',
      MANAGE: 'manage',
    },
  },
  MEDIAS: {
    value: 'medias',
    actions: {
      VIEW: 'view',
      UPLOAD: 'upload',
      DELETE: 'delete',
      EDIT: 'edit',
      DOWNLOAD: 'download',
      SHARE: 'share',
      BULK_UPLOAD: 'bulk_upload',
      BULK_DELETE: 'bulk_delete',
      CONVERT: 'convert',
      OPTIMIZE: 'optimize',
      WATERMARK: 'watermark',
      EMBED: 'embed',
      MANAGE_GALLERIES: 'manage_galleries',
      MANAGE_FOLDERS: 'manage_folders',
      SET_PERMISSIONS: 'set_permissions',
      ADMIN: 'admin',
    },
  },
  SETTINGS: {
    value: 'settings',
    actions: {
      GENERAL: 'general',
      SEO: 'seo',
      EMAIL: 'email',
      SECURITY: 'security',
      PAYMENT: 'payment',
      APPEARANCE: 'appearance',
      NOTIFICATIONS: 'notifications',
      INTEGRATIONS: 'integrations',
      MAINTENANCE: 'maintenance',
      CACHE: 'cache',
      PERFORMANCE: 'performance',
    },
  },
  REPORTS: {
    value: 'reports',
    actions: {
      VIEW_TRAFFIC: 'view_traffic',
      VIEW_CONTENT: 'view_content',
      VIEW_USER: 'view_user',
      VIEW_FINANCIAL: 'view_financial',
      VIEW_SYSTEM: 'view_system',
      EXPORT: 'export',
      SCHEDULE: 'schedule',
      CUSTOMIZE: 'customize',
    },
  },
  ANALYTICS: {
    value: 'analytics',
    actions: {
      ACCESS: 'access',
      VIEW_DETAILED: 'view_detailed',
      EXPORT_DATA: 'export_data',
      VIEW_USER_BEHAVIOR: 'view_user_behavior',
      VIEW_CONTENT_PERFORMANCE: 'view_content_performance',
      VIEW_TRAFFIC_SOURCES: 'view_traffic_sources',
      VIEW_ENGAGEMENT_METRICS: 'view_engagement_metrics',
    },
  },
  NEWSLETTERS: {
    value: 'newsletters',
    actions: {
      VIEW: 'view',
      CREATE: 'create',
      EDIT: 'edit',
      DELETE: 'delete',
      SEND: 'send',
      SCHEDULE: 'schedule',
      MANAGE_SUBSCRIBERS: 'manage_subscribers',
      VIEW_STATS: 'view_stats',
    },
  },
  BREAKING_NEWS: {
    value: 'breaking_news',
    actions: {
      CREATE: 'create',
      EDIT: 'edit',
      DELETE: 'delete',
      PUBLISH: 'publish',
      ARCHIVE: 'archive',
      PRIORITIZE: 'prioritize',
      NOTIFY: 'notify',
    },
  },
  LIVE_UPDATES: {
    value: 'live_updates',
    actions: {
      CREATE: 'create',
      EDIT: 'edit',
      DELETE: 'delete',
      PUBLISH: 'publish',
      MODERATE: 'moderate',
      MANAGE: 'manage',
    },
  },
  WORKFLOW: {
    value: 'workflow',
    actions: {
      VIEW: 'view',
      APPROVE: 'approve',
      REJECT: 'reject',
      REQUEST_CHANGES: 'request_changes',
      ASSIGN: 'assign',
      DELEGATE: 'delegate',
      ESCALATE: 'escalate',
      VIEW_HISTORY: 'view_history',
    },
  },
  SOCIAL_MEDIA: {
    value: 'social_media',
    actions: {
      CONNECT: 'connect',
      POST: 'post',
      SCHEDULE: 'schedule',
      MANAGE: 'manage',
      VIEW_INSIGHTS: 'view_insights',
      MODERATE: 'moderate',
    },
  },
  ADVERTISEMENTS: {
    value: 'advertisements',
    actions: {
      VIEW: 'view',
      CREATE: 'create',
      EDIT: 'edit',
      DELETE: 'delete',
      PUBLISH: 'publish',
      MANAGE_CAMPAIGNS: 'manage_campaigns',
      VIEW_ANALYTICS: 'view_analytics',
    },
  },
  NOTIFICATIONS: {
    value: 'notifications',
    actions: {
      VIEW: 'view',
      CREATE: 'create',
      SEND: 'send',
      MANAGE_TEMPLATES: 'manage_templates',
      CONFIGURE: 'configure',
    },
  },
  BACKUPS: {
    value: 'backups',
    actions: {
      CREATE: 'create',
      RESTORE: 'restore',
      DELETE: 'delete',
      DOWNLOAD: 'download',
      SCHEDULE: 'schedule',
    },
  },
  LOGS: {
    value: 'logs',
    actions: {
      VIEW: 'view',
      EXPORT: 'export',
      DELETE: 'delete',
      MONITOR: 'monitor',
    },
  },
  INTEGRATIONS: {
    value: 'integrations',
    actions: {
      MANAGE: 'manage',
      CONFIGURE: 'configure',
      TEST: 'test',
      VIEW_STATUS: 'view_status',
    },
  },
  CONTENT_TEMPLATES: {
    value: 'content_templates',
    actions: {
      VIEW: 'view',
      CREATE: 'create',
      EDIT: 'edit',
      DELETE: 'delete',
      SHARE: 'share',
      APPLY: 'apply',
    },
  },
  SEO: {
    value: 'seo',
    actions: {
      MANAGE_META: 'manage_meta',
      MANAGE_SITEMAP: 'manage_sitemap',
      MANAGE_ROBOTS: 'manage_robots',
      ANALYZE_KEYWORDS: 'analyze_keywords',
      OPTIMIZE_CONTENT: 'optimize_content',
    },
  },
  API_KEYS: {
    value: 'api_keys',
    actions: {
      VIEW: 'view',
      CREATE: 'create',
      EDIT: 'edit',
      DELETE: 'delete',
      REGENERATE: 'regenerate',
    },
  },
  WEBHOOKS: {
    value: 'webhooks',
    actions: {
      VIEW: 'view',
      CREATE: 'create',
      EDIT: 'edit',
      DELETE: 'delete',
      TEST: 'test',
    },
  },
};

function generateAllPermissions() {
  return Object.values(DOMAINS).map(domainObj => ({
    domain: domainObj.value,
    actions: Object.values(domainObj.actions),
  }));
}

export const ALL_PERMISSIONS = generateAllPermissions();
