import { DOMAINS } from './permissions';

export const DEFAULT_ROLES = [
  {
    code: 'reader',
    label: 'Độc giả',
    permissions: [
      { domain: DOMAINS.ARTICLES.value, action: DOMAINS.ARTICLES.actions.VIEW },
      { domain: DOMAINS.COMMENTS.value, action: DOMAINS.COMMENTS.actions.CREATE },
      { domain: DOMAINS.COMMENTS.value, action: DOMAINS.COMMENTS.actions.REPORT },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.VIEW_PROFILE },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.EDIT_PROFILE },
    ],
  },
  {
    code: 'reporter',
    label: 'Phóng viên',
    permissions: [
      { domain: DOMAINS.ARTICLES.value, action: DOMAINS.ARTICLES.actions.VIEW },
      { domain: DOMAINS.ARTICLES.value, action: DOMAINS.ARTICLES.actions.CREATE },
      { domain: DOMAINS.ARTICLES.value, action: DOMAINS.ARTICLES.actions.EDIT_OWN },
      { domain: DOMAINS.ARTICLES.value, action: DOMAINS.ARTICLES.actions.DELETE_OWN },
      { domain: DOMAINS.COMMENTS.value, action: DOMAINS.COMMENTS.actions.VIEW },
      { domain: DOMAINS.COMMENTS.value, action: DOMAINS.COMMENTS.actions.CREATE },
      { domain: DOMAINS.COMMENTS.value, action: DOMAINS.COMMENTS.actions.REPORT },
      { domain: DOMAINS.MEDIAS.value, action: DOMAINS.MEDIAS.actions.VIEW },
      { domain: DOMAINS.MEDIAS.value, action: DOMAINS.MEDIAS.actions.UPLOAD },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.VIEW_PROFILE },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.EDIT_PROFILE },
    ],
  },
  {
    code: 'editor',
    label: 'Biên tập viên',
    permissions: [
      { domain: DOMAINS.ARTICLES.value, action: DOMAINS.ARTICLES.actions.VIEW },
      { domain: DOMAINS.ARTICLES.value, action: DOMAINS.ARTICLES.actions.CREATE },
      { domain: DOMAINS.ARTICLES.value, action: DOMAINS.ARTICLES.actions.EDIT_ALL },
      { domain: DOMAINS.ARTICLES.value, action: DOMAINS.ARTICLES.actions.DELETE_ALL },
      { domain: DOMAINS.ARTICLES.value, action: DOMAINS.ARTICLES.actions.PUBLISH },
      { domain: DOMAINS.ARTICLES.value, action: DOMAINS.ARTICLES.actions.UNPUBLISH },
      { domain: DOMAINS.ARTICLES.value, action: DOMAINS.ARTICLES.actions.REVIEW },
      { domain: DOMAINS.ARTICLES.value, action: DOMAINS.ARTICLES.actions.MODERATE },
      { domain: DOMAINS.ARTICLES.value, action: DOMAINS.ARTICLES.actions.FEATURE },
      { domain: DOMAINS.ARTICLES.value, action: DOMAINS.ARTICLES.actions.PIN },
      { domain: DOMAINS.ARTICLES.value, action: DOMAINS.ARTICLES.actions.SCHEDULE },
      { domain: DOMAINS.COMMENTS.value, action: DOMAINS.COMMENTS.actions.VIEW },
      { domain: DOMAINS.COMMENTS.value, action: DOMAINS.COMMENTS.actions.MODERATE },
      { domain: DOMAINS.COMMENTS.value, action: DOMAINS.COMMENTS.actions.REPLY },
      { domain: DOMAINS.COMMENTS.value, action: DOMAINS.COMMENTS.actions.LIKE },
      { domain: DOMAINS.MEDIAS.value, action: DOMAINS.MEDIAS.actions.VIEW },
      { domain: DOMAINS.MEDIAS.value, action: DOMAINS.MEDIAS.actions.UPLOAD },
      { domain: DOMAINS.MEDIAS.value, action: DOMAINS.MEDIAS.actions.DELETE },
      { domain: DOMAINS.MEDIAS.value, action: DOMAINS.MEDIAS.actions.EDIT },
      { domain: DOMAINS.MEDIAS.value, action: DOMAINS.MEDIAS.actions.DOWNLOAD },
      { domain: DOMAINS.MEDIAS.value, action: DOMAINS.MEDIAS.actions.SHARE },
      { domain: DOMAINS.CATEGORIES.value, action: DOMAINS.CATEGORIES.actions.VIEW },
      { domain: DOMAINS.CATEGORIES.value, action: DOMAINS.CATEGORIES.actions.MANAGE },
      { domain: DOMAINS.CATEGORIES.value, action: DOMAINS.CATEGORIES.actions.CREATE },
      { domain: DOMAINS.CATEGORIES.value, action: DOMAINS.CATEGORIES.actions.EDIT },
      { domain: DOMAINS.CATEGORIES.value, action: DOMAINS.CATEGORIES.actions.DELETE },
      { domain: DOMAINS.TAGS.value, action: DOMAINS.TAGS.actions.VIEW },
      { domain: DOMAINS.TAGS.value, action: DOMAINS.TAGS.actions.MANAGE },
      { domain: DOMAINS.TAGS.value, action: DOMAINS.TAGS.actions.CREATE },
      { domain: DOMAINS.TAGS.value, action: DOMAINS.TAGS.actions.EDIT },
      { domain: DOMAINS.TAGS.value, action: DOMAINS.TAGS.actions.DELETE },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.VIEW_ALL },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.VIEW_PROFILE },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.EDIT_PROFILE },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.CREATE },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.DELETE },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.BLOCK },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.RESET_PASSWORD },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.VERIFY },
    ],
  },
  {
    code: 'super_admin',
    label: 'Super Admin',
    isAdmin: true,
    isSuperAdmin: true,
    permissions: [],
  },
  {
    code: 'admin',
    label: 'Admin',
    isAdmin: true,
    permissions: [],
  },
  {
    code: 'user_manager',
    label: 'Quản lý người dùng',
    permissions: [
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.VIEW_ALL },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.VIEW_PROFILE },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.EDIT_PROFILE },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.CREATE },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.DELETE },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.BLOCK },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.RESET_PASSWORD },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.VERIFY },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.ASSIGN_ROLE },
      { domain: DOMAINS.ROLES.value, action: DOMAINS.ROLES.actions.VIEW },
    ],
  },
  {
    code: 'role_manager',
    label: 'Quản lý vai trò và phân quyền',
    permissions: [
      { domain: DOMAINS.ROLES.value, action: DOMAINS.ROLES.actions.VIEW },
      { domain: DOMAINS.ROLES.value, action: DOMAINS.ROLES.actions.CREATE },
      { domain: DOMAINS.ROLES.value, action: DOMAINS.ROLES.actions.EDIT },
      { domain: DOMAINS.ROLES.value, action: DOMAINS.ROLES.actions.DELETE },
      { domain: DOMAINS.ROLES.value, action: DOMAINS.ROLES.actions.ASSIGN_PERMISSION },
    ],
  },
  {
    code: 'support_staff',
    label: 'Nhân viên hỗ trợ',
    permissions: [
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.VIEW_ALL },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.VIEW_PROFILE },
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.RESET_PASSWORD },
    ],
  },
  {
    code: 'auditor',
    label: 'Kiểm toán viên',
    permissions: [
      { domain: DOMAINS.USERS.value, action: DOMAINS.USERS.actions.VIEW_ALL },
      { domain: DOMAINS.ROLES.value, action: DOMAINS.ROLES.actions.VIEW },
    ],
  },
];
