import { DOMAINS } from './permissions';

export const DEFAULT_ROLES = [
  {
    code: 'reader',
    label: 'Độc giả',
    permissions: [
      { domain: DOMAINS.ARTICLE.value, action: DOMAINS.ARTICLE.actions.VIEW },
      { domain: DOMAINS.COMMENT.value, action: DOMAINS.COMMENT.actions.CREATE },
      { domain: DOMAINS.COMMENT.value, action: DOMAINS.COMMENT.actions.REPORT },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.VIEW_PROFILE },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.EDIT_PROFILE },
    ],
  },
  {
    code: 'reporter',
    label: 'Phóng viên',
    permissions: [
      { domain: DOMAINS.ARTICLE.value, action: DOMAINS.ARTICLE.actions.VIEW },
      { domain: DOMAINS.ARTICLE.value, action: DOMAINS.ARTICLE.actions.CREATE },
      { domain: DOMAINS.ARTICLE.value, action: DOMAINS.ARTICLE.actions.EDIT_OWN },
      { domain: DOMAINS.ARTICLE.value, action: DOMAINS.ARTICLE.actions.DELETE_OWN },
      { domain: DOMAINS.COMMENT.value, action: DOMAINS.COMMENT.actions.VIEW },
      { domain: DOMAINS.COMMENT.value, action: DOMAINS.COMMENT.actions.CREATE },
      { domain: DOMAINS.COMMENT.value, action: DOMAINS.COMMENT.actions.REPORT },
      { domain: DOMAINS.MEDIA.value, action: DOMAINS.MEDIA.actions.VIEW },
      { domain: DOMAINS.MEDIA.value, action: DOMAINS.MEDIA.actions.UPLOAD },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.VIEW_PROFILE },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.EDIT_PROFILE },
    ],
  },
  {
    code: 'editor',
    label: 'Biên tập viên',
    permissions: [
      { domain: DOMAINS.ARTICLE.value, action: DOMAINS.ARTICLE.actions.VIEW },
      { domain: DOMAINS.ARTICLE.value, action: DOMAINS.ARTICLE.actions.CREATE },
      { domain: DOMAINS.ARTICLE.value, action: DOMAINS.ARTICLE.actions.EDIT_ALL },
      { domain: DOMAINS.ARTICLE.value, action: DOMAINS.ARTICLE.actions.DELETE_ALL },
      { domain: DOMAINS.ARTICLE.value, action: DOMAINS.ARTICLE.actions.PUBLISH },
      { domain: DOMAINS.ARTICLE.value, action: DOMAINS.ARTICLE.actions.UNPUBLISH },
      { domain: DOMAINS.ARTICLE.value, action: DOMAINS.ARTICLE.actions.REVIEW },
      { domain: DOMAINS.ARTICLE.value, action: DOMAINS.ARTICLE.actions.MODERATE },
      { domain: DOMAINS.ARTICLE.value, action: DOMAINS.ARTICLE.actions.FEATURE },
      { domain: DOMAINS.ARTICLE.value, action: DOMAINS.ARTICLE.actions.PIN },
      { domain: DOMAINS.ARTICLE.value, action: DOMAINS.ARTICLE.actions.SCHEDULE },
      { domain: DOMAINS.COMMENT.value, action: DOMAINS.COMMENT.actions.VIEW },
      { domain: DOMAINS.COMMENT.value, action: DOMAINS.COMMENT.actions.MODERATE },
      { domain: DOMAINS.COMMENT.value, action: DOMAINS.COMMENT.actions.REPLY },
      { domain: DOMAINS.COMMENT.value, action: DOMAINS.COMMENT.actions.LIKE },
      { domain: DOMAINS.MEDIA.value, action: DOMAINS.MEDIA.actions.VIEW },
      { domain: DOMAINS.MEDIA.value, action: DOMAINS.MEDIA.actions.UPLOAD },
      { domain: DOMAINS.MEDIA.value, action: DOMAINS.MEDIA.actions.DELETE },
      { domain: DOMAINS.MEDIA.value, action: DOMAINS.MEDIA.actions.EDIT },
      { domain: DOMAINS.MEDIA.value, action: DOMAINS.MEDIA.actions.DOWNLOAD },
      { domain: DOMAINS.MEDIA.value, action: DOMAINS.MEDIA.actions.SHARE },
      { domain: DOMAINS.CATEGORY.value, action: DOMAINS.CATEGORY.actions.VIEW },
      { domain: DOMAINS.CATEGORY.value, action: DOMAINS.CATEGORY.actions.MANAGE },
      { domain: DOMAINS.CATEGORY.value, action: DOMAINS.CATEGORY.actions.CREATE },
      { domain: DOMAINS.CATEGORY.value, action: DOMAINS.CATEGORY.actions.EDIT },
      { domain: DOMAINS.CATEGORY.value, action: DOMAINS.CATEGORY.actions.DELETE },
      { domain: DOMAINS.TAG.value, action: DOMAINS.TAG.actions.VIEW },
      { domain: DOMAINS.TAG.value, action: DOMAINS.TAG.actions.MANAGE },
      { domain: DOMAINS.TAG.value, action: DOMAINS.TAG.actions.CREATE },
      { domain: DOMAINS.TAG.value, action: DOMAINS.TAG.actions.EDIT },
      { domain: DOMAINS.TAG.value, action: DOMAINS.TAG.actions.DELETE },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.VIEW_ALL },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.VIEW_PROFILE },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.EDIT_PROFILE },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.CREATE },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.DELETE },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.BLOCK },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.RESET_PASSWORD },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.VERIFY },
    ],
  },
  {
    code: 'super_admin',
    label: 'Super Admin',
    isAdmin: true,
    isSuperAdmin: true,
    permissions: [],
  },
  {
    code: 'admin',
    label: 'Admin',
    isAdmin: true,
    permissions: [],
  },
  {
    code: 'user_manager',
    label: 'Quản lý người dùng',
    permissions: [
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.VIEW_ALL },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.VIEW_PROFILE },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.EDIT_PROFILE },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.CREATE },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.DELETE },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.BLOCK },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.RESET_PASSWORD },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.VERIFY },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.ASSIGN_ROLE },
      { domain: DOMAINS.ROLE.value, action: DOMAINS.ROLE.actions.VIEW },
    ],
  },
  {
    code: 'role_manager',
    label: 'Quản lý vai trò và phân quyền',
    permissions: [
      { domain: DOMAINS.ROLE.value, action: DOMAINS.ROLE.actions.VIEW },
      { domain: DOMAINS.ROLE.value, action: DOMAINS.ROLE.actions.CREATE },
      { domain: DOMAINS.ROLE.value, action: DOMAINS.ROLE.actions.EDIT },
      { domain: DOMAINS.ROLE.value, action: DOMAINS.ROLE.actions.DELETE },
      { domain: DOMAINS.ROLE.value, action: DOMAINS.ROLE.actions.ASSIGN_PERMISSION },
    ],
  },
  {
    code: 'support_staff',
    label: 'Nhân viên hỗ trợ',
    permissions: [
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.VIEW_ALL },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.VIEW_PROFILE },
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.RESET_PASSWORD },
    ],
  },
  {
    code: 'auditor',
    label: 'Kiểm toán viên',
    permissions: [
      { domain: DOMAINS.USER.value, action: DOMAINS.USER.actions.VIEW_ALL },
      { domain: DOMAINS.ROLE.value, action: DOMAINS.ROLE.actions.VIEW },
    ],
  },
];
